var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                 yyy y y yyy yyyy                               ",
   "                                 y   yyy y!! yy y                               ",
   "                                 yyy y y yyy y  y                               ",
   "                              yy                                                ",
   "                              y y y y y yyy                                     ",
   "                              y y y y y y!!                                     ",
   "                              yy  y  y  yyy                                     ",
   "                                                  o                             ",
   "                                              @                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxx     xxxxxxx     Gxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxx           xxxxxxx        GxxxG                xxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxx                xxx           x                       xxxxxxxxxxxxxxx",
   "xxxx                         x           G            o              xxxxxxxxxxx",
   "xxxx o^                      G                                         xxxxxxxxx",
   "xxxxxxxx                                                                xxxxxxxx",
   "xxxxxxxxxx                                                                  xxxx",
   "xxxxxxxxxxxx                                                              xxxxxx",
   "xxxxxxxxxxxxxx                                                               xxx",
   "xxxxxxxxxxxxxxxx                                                              xx",
   "xxxxxxxxxxxxxxxxxxxxxx                                oo                    xxxx",
   "xxxxxxxxxxxxxxxxxxxx                  o          xxxxxxxxxxxxR                xx",
   "xxxxxxxxxxxxxxxxxxxx                o            G   xxxx                      x",
   "xxxx                              o     xxxxx         xx                      xx",
   "xxxx                                        G        xxxx      x              xx",
   "xxxx                          xxxx               xxxxxxxxxxxx  xxxxR          vx",
   "xxxx   @              %                              xxxx      xx      o       x",
   "xxxxxxxxxxxxxxx    xxxxxxx             xxxxxxxx o o o xx       xx      o       x",
   "xxxxxxxxxxxxxxx!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!xx      o       x",
   "!!!!!!!!!!!!!xx!!!!xx!!!!!!!!xxxxxxxx!!!!!!!!xxxxxxxxxxx!!!!!!!xx      o   %   x",
   "!!!!!!!!!!!!!xx!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx      o   x!!!x",
   "!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                      Gxx$$$$$$$$$$$$$$$$$xx                xxxx  ",
   "                                                                       Gxx$$$$$$$$$$$$$$$xx                  xx   ",
   "                                                                        Gxx$$$$$$$$$$$$$xx                  xx    ",
   "                                                                         Gxx$$$$$$$$$$$xx                  xx     ",
   "                                                                          Gxx$$$$$$$$$xx                    xx    ",
   "                                                                o^         Gxxxxxxxxxxx                      xx   ",
   "                                                               xxx          Gxxxxxxxxx                       Gx   ",
   "                                                               x$x           G  xxx                           G   ",
   "           o                                                   xGx              xxx                               ",
   "=         Rx                                                         xx=          xxx                             ",
   "                                                                      xx          xxx                             ",
   "                                                                       xx=        xxx                             ",
   "                                                    @  xx               xx        x                               ",
   "                                                              $$$x       xx     xxx                       o       ",
   "                                                              $xxx        xx         xx    x    x    x    x       ",
   "                   x                                x         G            xx        xx!!!!x!!!!x!!!!x!!!!x!xR  xx",
   "xxxx               |                                v   o                   xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!x R xx",
   "$      R     R       x                         x  R    x|  % x$$$G                  xxxxxvxxxxvxxxxvxxxxvxxxx  Rxx",
   "xx                   |                              xxxxxxxxxxxxxx                    xx                    x R xx",
   "                       x x                                                             x                    xR  xx",
   "                       T v                                                                                  x R xx",
   "      T                                                                                                     x  Rxx",
   "R     x                                                                                                     x R xx",
   "xxxxxxx             xxx                                                                                 x   xR  xx",
   "                      x                                                                            x    x   x R xx",
   "=======!!!!!!!xx   %  x^                                                                  x  x  x  x  x x       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                       x R  x R   xR   x%      xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      R          o                     o  R         Rxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xx       xxx         xx        xxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      o                                                       ",
   "                                                   xxxxxxx                                                    ",
   "                                                   x     x                                                    ",
   "                                                   x     x                                                    ",
   "                                                   x     x                                                    ",
   "                                                   x  o  x                                                    ",
   "                                                   x     x                                                    ",
   "                                                 xxx     xxx                                                  ",
   "                                                 x         x                                                  ",
   "                                                 x         x                                                  ",
   "                                                 x         x                                                  ",
   "                                                 x         x                                                  ",
   "                                                 xxxx      x                                                  ",
   "                                                 x         x                                                  ",
   "                                               xxx         xxx                                                ",
   "                                               x             x                                                ",
   "                                               x             x                                                ",
   "                                               x          %  x                                                ",
   "                                               x          xxxxxxx                                             ",
   "                                               x             x                                                ",
   "                                               x             x                                                ",
   "                                             xxx   xxx                                                        ",
   "                                             x                                                                ",
   "                                             x          R     ^x    xxx                                       ",
   "                                             x  |    xxxxxxxxxxx                                              ",
   "                                             x                 x                                              ",
   "                                             x                 x                                              ",
   "                                   xxxxxxxxxxxxxxx  R          xxxxxxxxxxx                                    ",
   "                               xxxxTTTTTTTTTxx     x            v      xxx                                    ",
   "                               xRRRRRRRRRRRRxx         |               xxx                                    ",
   "                               xRRRRRRRRRRRRxx       x                 xxx                                    ",
   "                    xxxxxxxxx     xTRTRTRTRTxx              |          xxx                                    ",
   "G                    xxxxxxxx     xRTRTRTRToxx     x                   xxx                                    ",
   " G                         xxxxxxxxxxxxxxx  xxR                     |  xxx                                    ",
   "  G        x  R       x    xxxxxxxxxxxxxxx       x                     xxx                                    ",
   "  G                                      x                            oxxx                                    ",
   "   G       xR         x                  xxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxx                                    ",
   "                                                      xxxxx                                                   ",
   "                                                                                                              ",
   "                 %                                                                                            ",
   "             xxxxxx                                                                                           ",
   "             x                                                                                                ",
   "   x!!x  @   xRRRRRRR=RR=RRRR==RRRRR=RRRRRR=RR=RRRRRRR==RRRRRRRR=R=RRRRRR=RRRRR=RRR=RRR===RRRR=RRR=R=RR=RRR=RR",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                   y  y           y     y !                                                   ",
   "                                   y  y           y     y                                                     ",
   "                                    yyy yyy y y   y  y  y y y  y                                              ",
   "                                      y y y y y    y y y  y yy y                                              ",
   "                                   yyy  yyy yyy     y y   y y yy                                              ",
   "                                  xRRRRRRRRRRRRRRRRRRRRRRRRRRRRx                                              ",
   "                                  xR=R=R=R=R=R=R=R=R=xxxR=R=R=!x                                              ",
   "                                  x|v|v|v|v|v|v|v|v|vx@xv|v|v|!x                                              ",
   "                                  x%^%^%^%^%^%^%^%^%^xxx^%^%^%!x                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
